### ISSUE TITLE
Load more data from `subscribe`

### ISSUE THREAD

**Issue by Navyroot** [tanutapi/dart_meteor#17]
Hi all bro , I want to load more data from `subscribe` when scroll , how can I do?

**Comment by tanutapi** [comment]
Hi @Navyroot, your issue is beyond on this project. It's about how you handle your Meteor logic.

However, I can guide you on a simple solution here. You have to manage it with your Meteor.publish() function.

Basically, in your publish function:
```
Meteor.publish('pubName', function() {
	return YourCollections.find();
});
```
It will return all documents from your collection to the client. Think about if you have a million documents that have 1KB for each, 1GB of data has to be transferred to your client. The solution is that you have to have a limit on your publish function:
```
Meteor.publish('pubName', function() {
	return YourCollections.find({}, {limit: 1000});
});
```
The above function will only return the first 1000 documents. And if you want to load more documents you can do:
```
Meteor.publish('pubName', function(page) {
	return YourCollections.find({}, {skip: page * 1000, limit: 1000});
});
```
or you may use a limit. When you scroll down to the list you can subscribe to more documents with more limit value.
```
Meteor.publish('pubName', function(limit) {
	return YourCollections.find({}, {limit: limit});
});
```
I think you should try to implement your data loading in pure Meteor first. Then after it works, you can continue intregrate it in the Flutter project.
