### ISSUE TITLE
null-safety support

### ISSUE THREAD

**Issue by X-SLAYER** [tanutapi/dart_meteor#26]
Please consider migrating to null-safety.

**Comment by tanutapi** [comment]
Hi, I'm preparing a new major update. After that I will migrate it to null-safety.

**Comment by mHassan20896** [comment]
Are you guys launch null safety version now ??

**Comment by tanutapi** [comment]
It's still in my 2.0.0 branch. I have no time to test it in the real application yet.

**Comment by YouSour** [comment]
i wait for you guys upgrade this package to null safety version

**Comment by tanutapi** [comment]
I just upload the null-safety version to pub.dev. You guys can check it at https://pub.dev/packages/dart_meteor.

There are some breaking change on APIs to make it clearer. Most change will be shown as errors in your code after migrated to 2.0.0 and you can fix it easily. 

However, if you access a DateTime value (from the collection and method) in the past, please noted that currently 2.0.0 will return you a DateTime variable rather than {'$date': millisecondsSinceEpoch} so you might update your code to fix your runtime error.

**Comment by YouSour** [comment]
@tanutapi version 2 support web or not ? bro
