### ISSUE TITLE
Get custom fields from user

### ISSUE THREAD

**Issue by keepjhonnying** [tanutapi/dart_meteor#38]
Hi.

How to get custom fields from user?

Is through user method?

https://pub.dev/documentation/dart_meteor/latest/dart_meteor/MeteorClient/user.html

**Comment by keepjhonnying** [comment]
Thanks for the reply @tanutapi 

Yes. I'm using Flutter.

In the code:

            StreamBuilder(
              stream: meteor.user(),
              builder: (context, snapshot) {
                var a = snapshot.data as Map;
                return Text(a['username'].toString());
              },

            ),


`return Text(a['username'].toString());` return the username

but if i change to

`return Text(a['customfield'].toString());`

return null

And if

`print(a.toString());`

I see only default fields and fields under profile

```
{
username: myusername,
emails: [{address:
email@gmail.com, verified: false}],
profile: {fullName: Long Full Name},
_id: oGijmwaxqaX9DwT5j
}
```

**Comment by tanutapi** [comment]
Yes, that's the Meteor's behavior. Also, you may want to add a deny permission on user's profile object since by default the client allows to update their own profile. Ref: https://guide.meteor.com/accounts.html#dont-use-profile

If you plan to store some important information inside the `profile`, you must:

```
// Deny all client-side updates to user documents
Meteor.users.deny({
  update() { return true; }
});
```

Best,
