### ISSUE TITLE
Load more data using meteor.subscribe & meteor.collection

### ISSUE THREAD

**Issue by YouSour** [tanutapi/dart_meteor#56]
hi @tanutapi , i would like to know the right way load more data using meteor.subscribe & meteor.collection, could you show me any example code or demo ? thank in advance.
on server side i already did it, i don't know on client side (Flutter), here what it look like :

**Meteor Server Side**
```
import { Meteor } from 'meteor/meteor';
import Customers from '../customers'
import _ from 'lodash'
import moment from 'moment'

Meteor.publish('customers', ({ page, pageSize }) => {
  try {
    let selector = {}
    let options = {}

    if (!_.isNull(page) && !_.isNull(pageSize)) {
      let skip = (page - 1) * pageSize
      options.skip = skip
      options.limit = pageSize
    }

    return Customers.find(selector, options)
  } catch (error) {
    throw new Meteor.Error(error)
  }
})
```

**Comment by tanutapi** [comment]
Hi @YouSour,

This issue is a Meteor loading technique. You can see in the doc https://guide.meteor.com/data-loading.html#pagination

On the dart_meteor (Flutter) side, you can resubscribe with page and pageSize as arguments anytime you want. But don't forget to stop the old one first.

I, personally, do not do pagination in my own app.

**Comment by YouSour** [comment]
@tanutapi thank you for info , bro 😄
